### ISSUE TITLE
CSS `@container scroll-state` not working

### ISSUE THREAD

**Issue by valler** [microsoft/vscode-livepreview#723]
Styles applied via scroll-state queries don't apply.

For example:

```html
<div class="container">
  <div class="item">
    <div class="content">A</div>
    <div class="content">B</div>
    <div class="content">C</div>
    <div class="content">D</div>
    <div class="content">E</div>
    <div class="content">F</div>
  </div>
</div>
```

```css
div {
  --size: 3em;
  box-sizing: border-box;
}

.container {
  overflow: scroll;
  scroll-snap-type: y mandatory;
  width: var(--size);
  height: calc(3 * var(--size));
}

.item {
  scroll-snap-align: center;
  container-type: scroll-state;
  container-name: scroll-item;
  width: var(--size);
  height: var(--size);
  color: #000;
  background: #333;
}


@container scroll-item scroll-state(snapped: y) {
  .content {
    color: red;
    background: #999;
  }
}
```
